# Fitbit Exploration

In [98]:
import os
import sys
sys.path.append('../')

from src.features import build_features
from src.visualization import visualize
from src.reports import make_report

import pandas as pd
import numpy as np

from datetime import datetime, timedelta
import json
import ast

# Data Import

## Single Participant
Starting with one participant to see how to work with the data

In [422]:
pt = "1a9udoc5"
pt_dir = f"/Volumes/HEF_Dissertation_Research/utx000/extension/data/fitbit/{pt}"
single_info = pd.read_csv(f"{pt_dir}/fitbit_info.csv")
single_daily = pd.read_csv(f"{pt_dir}/fitbit_daily_records.csv")
single_intra = pd.read_csv(f"{pt_dir}/fitbit_intraday_records.csv",index_col=0,infer_datetime=True)

TypeError: parser_f() got an unexpected keyword argument 'infer_datetime'

### Info CSV
Below is an output of the ```fitbit_info.csv```

In [9]:
single_info.head()

,date,devices,friends,friends_leaderboard
0,2020-06-19 01:00:31.116944,"[{'battery': 'High', 'batteryLevel': 89, 'devi...",[],"[{'id': '86SZWS', 'type': 'ranked-user', 'step..."
1,2020-06-20 01:00:30.972641,"[{'battery': 'High', 'batteryLevel': 89, 'devi...",[],"[{'id': '86SZWS', 'type': 'ranked-user', 'step..."
2,2020-06-21 01:00:30.793194,"[{'battery': 'High', 'batteryLevel': 89, 'devi...",[],"[{'id': '86SZWS', 'type': 'ranked-user', 'step..."
3,2020-06-22 01:00:30.964714,"[{'battery': 'High', 'batteryLevel': 89, 'devi...",[],"[{'id': '86SZWS', 'type': 'ranked-user', 'step..."
4,2020-06-23 01:00:31.202136,"[{'battery': 'High', 'batteryLevel': 89, 'devi...",[],"[{'id': '86SZWS', 'type': 'ranked-user', 'step..."

In [261]:
devices = get_device_df(single_info)
devices.head()

,battery,batteryLevel,deviceVersion,features,id,lastSyncTime,mac,type
date,,,,,,,,
2020-06-19 01:00:31.116944,High,89,Inspire HR,[],1351786930,2020-06-17T07:43:29.000,C53F396828AA,TRACKER
2020-06-20 01:00:30.972641,High,89,Inspire HR,[],1351786930,2020-06-17T07:43:29.000,C53F396828AA,TRACKER
2020-06-21 01:00:30.793194,High,89,Inspire HR,[],1351786930,2020-06-17T07:43:29.000,C53F396828AA,TRACKER
2020-06-22 01:00:30.964714,High,89,Inspire HR,[],1351786930,2020-06-17T07:43:29.000,C53F396828AA,TRACKER
2020-06-23 01:00:31.202136,High,89,Inspire HR,[],1351786930,2020-06-17T07:43:29.000,C53F396828AA,TRACKER

The ```fitbit_info.csv``` seems to have good information for debugging purposes and tracking battery levels, but overall won't be useful for any analysis purposes.

### Daily CSV
Below is an out put of the ```daily_fitbit.csv``` file and a closer look at some of the more interesting entries.

In [7]:
single_daily.head()

,date,activities_calories,activities_caloriesBMR,activities_steps,activities_distance,activities_minutesSedentary,activities_minutesLightlyActive,activities_minutesFairlyActive,activities_minutesVeryActive,activities_activityCalories,body_bmi,body_fat,body_weight,foods_log_caloriesIn,foods_log_water,activities_heart,sleep
0,2020-05-01 00:00:00,1116.0,1116.0,0,0.0,1440,0,0,0,0.0,19.818027,0.0,96.99,0.0,0.0,"{'customHeartRateZones': [], 'heartRateZones':...",NaN
1,2020-05-02 00:00:00,1116.0,1116.0,0,0.0,1440,0,0,0,0.0,19.818027,0.0,96.99,0.0,0.0,"{'customHeartRateZones': [], 'heartRateZones':...",NaN
2,2020-05-03 00:00:00,1116.0,1116.0,0,0.0,1440,0,0,0,0.0,19.818027,0.0,96.99,0.0,0.0,"{'customHeartRateZones': [], 'heartRateZones':...",NaN
3,2020-05-04 00:00:00,1116.0,1116.0,0,0.0,1440,0,0,0,0.0,19.818027,0.0,96.99,0.0,0.0,"{'customHeartRateZones': [], 'heartRateZones':...",NaN
4,2020-05-05 00:00:00,1116.0,1116.0,0,0.0,1440,0,0,0,0.0,19.818027,0.0,96.99,0.0,0.0,"{'customHeartRateZones': [], 'heartRateZones':...",NaN

In [262]:
daily_slp = get_sleep_df(single_daily)
daily_slp.head()

,awakeCount,awakeDuration,awakeningsCount,dateOfSleep,duration,efficiency,endTime,logId,minuteData,minutesAfterWakeup,minutesAsleep,minutesAwake,minutesToFallAsleep,restlessCount,restlessDuration,startTime,timeInBed
date,,,,,,,,,,,,,,,,,
2020-05-23,0,0,12,2020-05-23,27600000,95,2020-05-23T07:08:30.000,27377408929,"[{'dateTime': '23:28:30', 'value': '2'}, {'dat...",0,437,23,0,12,23,2020-05-22T23:28:30.000,460
2020-05-24,1,1,9,2020-05-24,25500000,96,2020-05-24T07:52:00.000,27377408930,"[{'dateTime': '00:47:00', 'value': '1'}, {'dat...",0,406,19,0,8,18,2020-05-24T00:47:00.000,425
2020-05-25,1,3,15,2020-05-25,29880000,95,2020-05-25T07:24:30.000,27377408931,"[{'dateTime': '23:06:30', 'value': '1'}, {'dat...",0,472,26,0,14,23,2020-05-24T23:06:30.000,498
2020-05-26,0,0,11,2020-05-26,28080000,96,2020-05-26T07:27:00.000,27377408932,"[{'dateTime': '23:38:30', 'value': '2'}, {'dat...",0,449,19,0,11,19,2020-05-25T23:38:30.000,468
2020-05-27,1,1,9,2020-05-27,29100000,96,2020-05-27T07:12:30.000,27377408934,"[{'dateTime': '23:07:30', 'value': '2'}, {'dat...",0,465,20,0,8,19,2020-05-26T23:07:30.000,485

In [263]:
minute_slp = get_minute_sleep_df(daily_slp)
minute_slp.head()

   start_date    end_date      time value
0  2020-05-22  2020-05-23  23:28:30     2
1  2020-05-22  2020-05-23  23:29:30     2
2  2020-05-22  2020-05-23  23:30:30     2
3  2020-05-22  2020-05-23  23:31:30     2
4  2020-05-22  2020-05-23  23:32:30     2

### Intraday CSV

In [283]:
single_intra.head()

,date,activities_calories,activities_steps,activities_distance,activities_heart
0,2020-05-22 09:02:00,0.85272,NaN,NaN,NaN
1,2020-05-22 09:02:05,NaN,NaN,NaN,70.0
2,2020-05-22 09:02:20,NaN,NaN,NaN,70.0
3,2020-05-22 09:02:30,NaN,NaN,NaN,72.0
4,2020-05-22 09:02:35,NaN,NaN,NaN,76.0

The ```fitbit_daily.csv``` has a lot of good summary data including sleep summary values and sleep data by the minute.

## All Participants
Now that we have looked at the individual data files, now we can start to import all the data for all participants.

In [349]:
pt_dir = f"/Volumes/HEF_Dissertation_Research/utx000/extension/data/fitbit/"
fitbit_daily = import_fitbit("daily_records")
fitbit_info = import_fitbit("info")
fitbit_intra = import_fitbit("intraday_records")

	Reading from file daily_records
		Reading for participant 15tejjtw
		Reading for participant 1a9udoc5
		Reading for participant 1isvt8z8
		Reading for participant 28up4c3g
		Reading for participant 2vj84fjp
		Reading for participant 2vs5x6x9
		Reading for participant 2xtqkfz1
		Reading for participant 34483b37
		Reading for participant 3k5hntn3
		Reading for participant 3muzh3ip
		Reading for participant 3tn8jd1v
		Reading for participant 42epayem
		Reading for participant 43b1cd5m
		Reading for participant 4i7679py
		Reading for participant 5bg4j1pp
		Reading for participant 745vq78e
		Reading for participant 789gcb6u
		Reading for participant 7esq1z48
		Reading for participant 8km1l6ms
		Reading for participant 8vpj3b9v
		Reading for participant 9h8gt1q6
		Reading for participant 9jtzsuu8
		Reading for participant 9q1adgjk
		Reading for participant 9xmhtq74
		Reading for participant a72ljpy4
		Reading for participant adv5yxrq
		Reading for participant amrqgbar
		Reading for participant axk49ssu
		Reading for participant bc1z575j
		Reading for participant bjhpm88s
		Reading for participant bl3h5apm
		Reading for participant cnpj2xu4
		Reading for participant d5qxvm2x
		Reading for participant d9x9hdc3
		Reading for participant ddvq13tt
		Reading for participant dv7kt6ue
		Reading for participant e73a1pd5
		Reading for participant egbyyyeo
		Reading for participant ewvz3zm1
		Reading for participant fjor6fof
		Reading for participant gccj6zrv
		Reading for participant gu5qletd
		Reading for participant h3he4prx
		Reading for participant h8aoiyhv
		Reading for participant hcpu5myv
		Reading for participant hfttkth7
		Reading for participant hrqrneay
		Reading for participant hxj6brwj
		Reading for participant ijz9gssj
		Reading for participant itmylz3g
		Reading for participant itn82o6p
		Reading for participant kyj367pi
		Reading for participant lkkjddam
		Reading for participant loxhw1gk
		Reading for participant mp48w543
		Reading for participant mv14b8aj
		Reading for participant nmmo2594
		Reading for participant nonlw2g8
		Reading for participant o6xwrota
		Reading for participant obb7z8jm
		Reading for participant olaxadz5
		Reading for participant oxcpr7e3
		Reading for participant pfsvsd9j
		Reading for participant pgvvwyvh
		Reading for participant phdiu7p3
		Reading for participant q5y11ytm
		Reading for participant qh34m4r9
		Reading for participant qpro16vm
		Reading for participant r11k6uxz
		Reading for participant rj4lxgvp
		Reading for participant rnse61g4
		Reading for participant rvhdl2la
		Reading for participant shi1ykro
		Reading for participant t4jphih6
		Reading for participant tfhg94sp
		Reading for participant tlmlq19s
		Reading for participant tmexej5v
		Reading for participant u5wdcmwh
		Reading for participant uu6knbbx
		Reading for participant uz52kilo
		Reading for participant vdtyoovh
		Reading for participant vpy1a985
		Reading for participant vr9j5rry
		Reading for participant wlwwibi7
		Reading for participant wnprz3dq
		Reading for participant xdbdrk6e
		Reading for participant xlw5ntd5
		Reading for participant xxvnhauv
		Reading for participant y1tvkx14
		Reading for participant zdpffrox
	Reading from file info
		Reading for participant 15tejjtw
		Reading for participant 1a9udoc5
		Reading for participant 1isvt8z8
		Reading for participant 28up4c3g
		Reading for participant 2vj84fjp
		Reading for participant 2vs5x6x9
		Reading for participant 2xtqkfz1
		Reading for participant 34483b37
		Reading for participant 3k5hntn3
		Reading for participant 3muzh3ip
		Reading for participant 3tn8jd1v
		Reading for participant 42epayem
		Reading for participant 43b1cd5m
		Reading for participant 4i7679py
		Reading for participant 5bg4j1pp
		Reading for participant 745vq78e
		Reading for participant 789gcb6u
		Reading for participant 7esq1z48
		Reading for participant 8km1l6ms
		Reading for participant 8vpj3b9v
		Reading for participant 9h8gt1q6
		Reading for participant 9jtzsuu8
		Reading for participant 9q1adgjk
		Reading for participant 9xmhtq74
		Reading for participant a72ljpy4
		Reading for participant adv5yxrq
		Reading for participant amrqgbar
		Reading for participant axk49ssu
		Reading for participant bc1z575j
		Reading for participant bjhpm88s
		Reading for participant bl3h5apm
		Reading for participant cnpj2xu4
		Reading for participant d5qxvm2x
		Reading for participant d9x9hdc3
		Reading for participant ddvq13tt
		Reading for participant dv7kt6ue
		Reading for participant e73a1pd5
		Reading for participant egbyyyeo
		Reading for participant ewvz3zm1
		Reading for participant fjor6fof
		Reading for participant gccj6zrv
		Reading for participant gu5qletd
		Reading for participant h3he4prx
		Reading for participant h8aoiyhv
		Reading for participant hcpu5myv
		Reading for participant hfttkth7
		Reading for participant hrqrneay
		Reading for participant hxj6brwj
		Reading for participant ijz9gssj
		Reading for participant itmylz3g
		Reading for participant itn82o6p
		Reading for participant kyj367pi
		Reading for participant lkkjddam
		Reading for participant loxhw1gk
		Reading for participant mp48w543
		Reading for participant mv14b8aj
		Reading for participant nmmo2594
		Reading for participant nonlw2g8
		Reading for participant o6xwrota
		Reading for participant obb7z8jm
		Reading for participant olaxadz5
		Reading for participant oxcpr7e3
		Reading for participant pfsvsd9j
		Reading for participant pgvvwyvh
		Reading for participant phdiu7p3
		Reading for participant q5y11ytm
		Reading for participant qh34m4r9
		Reading for participant qpro16vm
		Reading for participant r11k6uxz
		Reading for participant rj4lxgvp
		Reading for participant rnse61g4
		Reading for participant rvhdl2la
		Reading for participant shi1ykro
		Reading for participant t4jphih6
		Reading for participant tfhg94sp
		Reading for participant tlmlq19s
		Reading for participant tmexej5v
		Reading for participant u5wdcmwh
		Reading for participant uu6knbbx
		Reading for participant uz52kilo
		Reading for participant vdtyoovh
		Reading for participant vpy1a985
		Reading for participant vr9j5rry
		Reading for participant wlwwibi7
		Reading for participant wnprz3dq
		Reading for participant xdbdrk6e
		Reading for participant xlw5ntd5
		Reading for participant xxvnhauv
		Reading for participant y1tvkx14
		Reading for participant zdpffrox
	Reading from file intraday_records
		Reading for participant 15tejjtw
		Reading for participant 1a9udoc5
		Reading for participant 1isvt8z8
		Dataframe is most likely empty (0)
		Reading for participant 28up4c3g
		Dataframe is most likely empty (0)
		Reading for participant 2vj84fjp
		Dataframe is most likely empty (0)
		Reading for participant 2vs5x6x9
		Dataframe is most likely empty (0)
		Reading for participant 2xtqkfz1
		Dataframe is most likely empty (0)
		Reading for participant 34483b37
		Dataframe is most likely empty (0)
		Reading for participant 3k5hntn3
		Dataframe is most likely empty (0)
		Reading for participant 3muzh3ip
		Dataframe is most likely empty (0)
		Reading for participant 3tn8jd1v
		Dataframe is most likely empty (0)
		Reading for participant 42epayem
		Dataframe is most likely empty (0)
		Reading for participant 43b1cd5m
		File intraday_records not found for participant 43b1cd5m
		Reading for participant 4i7679py
		Reading for participant 5bg4j1pp
		Dataframe is most likely empty (0)
		Reading for participant 745vq78e
		Reading for participant 789gcb6u
		Reading for participant 7esq1z48
		Dataframe is most likely empty (0)
		Reading for participant 8km1l6ms
		Dataframe is most likely empty (0)
		Reading for participant 8vpj3b9v
		Reading for participant 9h8gt1q6
		Dataframe is most likely empty (0)
		Reading for participant 9jtzsuu8
		Reading for participant 9q1adgjk
		Reading for participant 9xmhtq74
		Reading for participant a72ljpy4
		Dataframe is most likely empty (0)
		Reading for participant adv5yxrq
		Dataframe is most likely empty (0)
		Reading for participant amrqgbar
		Dataframe is most likely empty (0)
		Reading for participant axk49ssu
		Reading for participant bc1z575j
		Dataframe is most likely empty (0)
		Reading for participant bjhpm88s
		Dataframe is most likely empty (0)
		Reading for participant bl3h5apm
		Dataframe is most likely empty (0)
		Reading for participant cnpj2xu4
		Dataframe is most likely empty (0)
		Reading for participant d5qxvm2x
		Dataframe is most likely empty (0)
		Reading for participant d9x9hdc3
		Dataframe is most likely empty (0)
		Reading for participant ddvq13tt
		Dataframe is most likely empty (0)
		Reading for participant dv7kt6ue
		Dataframe is most likely empty (0)
		Reading for participant e73a1pd5

		Reading for participant egbyyyeo
		Dataframe is most likely empty (0)
		Reading for participant ewvz3zm1
		Reading for participant fjor6fof
		Dataframe is most likely empty (0)
		Reading for participant gccj6zrv
		Dataframe is most likely empty (0)
		Reading for participant gu5qletd
		Dataframe is most likely empty (0)
		Reading for participant h3he4prx
		Dataframe is most likely empty (0)
		Reading for participant h8aoiyhv
		Reading for participant hcpu5myv
		Reading for participant hfttkth7
		Dataframe is most likely empty (0)
		Reading for participant hrqrneay
		Dataframe is most likely empty (0)
		Reading for participant hxj6brwj
		Reading for participant ijz9gssj
		Dataframe is most likely empty (0)
		Reading for participant itmylz3g
		Reading for participant itn82o6p
		Dataframe is most likely empty (0)
		Reading for participant kyj367pi
		File intraday_records not found for participant kyj367pi
		Reading for participant lkkjddam
		Reading for participant loxhw1gk
		Dataframe is most likely empty (0)
		Reading for participant mp48w543
		Dataframe is most likely empty (0)
		Reading for participant mv14b8aj
		Dataframe is most likely empty (0)
		Reading for participant nmmo2594
		Dataframe is most likely empty (0)
		Reading for participant nonlw2g8
		Dataframe is most likely empty (0)
		Reading for participant o6xwrota
		Reading for participant obb7z8jm
		Dataframe is most likely empty (0)
		Reading for participant olaxadz5
		Reading for participant oxcpr7e3
		Reading for participant pfsvsd9j
		Dataframe is most likely empty (0)
		Reading for participant pgvvwyvh
		Dataframe is most likely empty (0)
		Reading for participant phdiu7p3
		Dataframe is most likely empty (0)
		Reading for participant q5y11ytm
		Dataframe is most likely empty (0)
		Reading for participant qh34m4r9
		Reading for participant qpro16vm
		Dataframe is most likely empty (0)
		Reading for participant r11k6uxz
		Dataframe is most likely empty (0)
		Reading for participant rj4lxgvp
		Dataframe is most likely empty (0)
		Reading for participant rnse61g4
		Reading for participant rvhdl2la
		Reading for participant shi1ykro
		Dataframe is most likely empty (0)
		Reading for participant t4jphih6
		Reading for participant tfhg94sp
		Dataframe is most likely empty (0)
		Reading for participant tlmlq19s
		Reading for participant tmexej5v
		Reading for participant u5wdcmwh
		Dataframe is most likely empty (0)
		Reading for participant uu6knbbx
		Dataframe is most likely empty (0)
		Reading for participant uz52kilo
		Dataframe is most likely empty (0)
		Reading for participant vdtyoovh
		Dataframe is most likely empty (0)
		Reading for participant vpy1a985
		Reading for participant vr9j5rry
		Reading for participant wlwwibi7
		Dataframe is most likely empty (0)
		Reading for participant wnprz3dq
		Reading for participant xdbdrk6e
		Reading for participant xlw5ntd5
		Reading for participant xxvnhauv
		Dataframe is most likely empty (0)
		Reading for participant y1tvkx14
		Reading for participant zdpffrox

In [348]:
def import_fitbit(filename, pt_dir=f"/Volumes/HEF_Dissertation_Research/utx000/extension/data/fitbit/"):
    '''
    
    '''
    print(f"\tReading from file {filename}")
    df = pd.DataFrame()
    for pt in os.listdir(pt_dir):
        if pt[0] != ".":
            print(f"\t\tReading for participant {pt}")
            try:
                temp = pd.read_csv(f"{pt_dir}{pt}/fitbit_{filename}.csv", index_col=0, parse_dates=True)
                if filename[:4] == "intr":
                    temp = process_fitbit_intraday(temp)
                
                temp["beiwe"] = pt
                df = df.append(temp)
            except FileNotFoundError:
                print(f"\t\tFile {filename} not found for participant {pt}")
                
    return df

# Functions
Below are a set of useful functions for handling the Fitbit Data

## Dictionary-esque Entries
There are a fair amount of entries that take on the form of a ```JSON``` or ```dict```. The functions below help turn them into a Dataframe of their very own!

In [405]:
def get_device_df(info_df):
    '''
    Take dictionary-like entries for fitbit info dataframe for each row in a dataframe and makes a new dataframe
    
    Inputs:
    - info_df: the fitbit info dataframe with the dictionary-like entries
    
    Returns a dataframe for the device column
    '''
    
    overall_dict = {}
    for row in range(len(info_df)):
        Dict = ast.literal_eval(info_df['devices'][row])
        if type(Dict) == dict:
            Dict = Dict
        elif type(Dict) in [tuple,list] and len(Dict) > 1:
            Dict = Dict[0]
        else:
            continue

        for key in Dict.keys():
            overall_dict.setdefault(key, [])
            overall_dict[key].append(Dict[key])
        # adding in the date of recording
        overall_dict.setdefault('date', [])
        overall_dict['date'].append(info_df.index[row])
        
    df = pd.DataFrame(overall_dict)
    df['date'] = pd.to_datetime(df['date'],errors='coerce')
    return df.set_index('date')

In [425]:
def get_sleep_df(daily_df):
    '''
    Creates a dataframe with the daily sleep data summarized
    
    Inputs:
    - daily_df: dataframe created from the daily fitbit csv file
    
    Returns a dataframe of the daily sleep data
    '''
    overall_dict = {}
    for row in range(len(daily_df)):
        if type(daily_df['sleep'][row]) == float:
            continue
        else:
            Dict = ast.literal_eval(daily_df['sleep'][row])
            if type(Dict) == dict:
                Dict = Dict
            else:
                Dict = Dict[0]
            for key in Dict.keys():
                overall_dict.setdefault(key, [])
                overall_dict[key].append(Dict[key])
            # adding in the date of recording
            overall_dict.setdefault('date', [])
            overall_dict['date'].append(daily_df.index[row])
            # adding beiwe id
            overall_dict.setdefault('beiwe', [])
            overall_dict['beiwe'].append(daily_df['beiwe'][row])

    df = pd.DataFrame(overall_dict)
    df['date'] = pd.to_datetime(df['date'],errors='coerce')
    return df.set_index('date')

In [426]:
def get_minute_sleep_df(daily_sleep):
    '''
    Creates a dataframe for the minute sleep data
    
    Input(s):
    - daily_sleep: dataframe holding the daily sleep data with a column called minuteData
    
    Returns a dataframe with the timestamp and number corresponding to sleep stage
    '''
    
    overall_dict = {'startDate':[],'endDate':[],'dateTime':[],'value':[],'beiwe':[]}
    for row in range(len(daily_sleep)):
        d0 = pd.to_datetime(daily_sleep['startTime'][row])
        d1 = pd.to_datetime(daily_sleep['dateOfSleep'][row])
        for minute_recording in daily_sleep['minuteData'][row]:
            for key in minute_recording.keys():
                overall_dict[key].append(minute_recording[key])
            # adding start and end dates for sleep period
            overall_dict['startDate'].append(d0.date())
            overall_dict['endDate'].append(d1.date())
            # adding beiwe id
            overall_dict['beiwe'].append(daily_sleep['beiwe'][row])
            
    df = pd.DataFrame(overall_dict)
    df.columns = ['start_date','end_date','time','value','beiwe']
    return df

## Intraday Processing
The function(s) below help process the ```fitbit_intraday.csv``` file.

In [329]:
def process_fitbit_intraday(raw_df,resample_rate=60):
    '''
    
    '''
    try:
        df = raw_df.resample(f'{resample_rate}T').mean()
    except TypeError:
        print(f"\t\tDataframe is most likely empty ({len(raw_df)})")
        return raw_df
    return df